version: '3.8'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: senha
      WORDPRESS_DB_NAME: banco
    volumes:
    - ./data/wordpress:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 20s
      retries: 10
