version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: meu_rabbitmq
        restart: always
        volumes:
            - ./data:/var/lib/rabbitmq
        ports:
            - 5672:7672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_USER: admin
