version: '3.8'

services:
    mariadb:
        image: mariadb:latest
        container_name: meu_mariadb
        restart: always
        ports:
            - 3307:3306
        environment:
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
            - ./conf:/etc/mysql/conf.d
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
