version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
        container_name: meu_elasticsearch
        restart: always
        environment:
            - discovery.type=single-node
            - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
            - xpack.security.enabled=false
        ports:
            - 9200:9200
        mem_limit: 1g
        volumes:
            - ./data:/usr/share/elasticsearch/data
