version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: meu_mongodb
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
            - ./conf/mongod.conf:/etc/mongo/mongod.conf
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s
    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
        depends_on:
            mongodb:
                condition: service_healthy
